[package]
name = "rcr2"
version = "0.1.0"
edition = "2021"

[dependencies]
serde-xml-rs = "0.6.0"
rusqlite = "0.33.0"
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }

